=== chrizel/Yzis/syntax/language.dtd
<!--
        Copyright (c) 2001 Joseph Wenninger <jowenn@kde.org>
        modified (c) 2002 Anders Lund <anders@alweb.dk>
        modified (c) 2003 Simon Huerlimann <simon.huerlimann@access.unizh.ch>

        This file describes the XML format used for syntax highlight descriptions
        for the Kate text editor (http://kate.kde.org), which is part of the KDE
        desktop environment (http://www.kde.org).
        You'll find the "Writing a Kate Highlighting XML File HOWTO" at
        http://kate.kde.org/doc/hlhowto.php

        This format is identified using the SYSTEM identifier
        SYSTEM "language.dtd"

        Files using this format should include a DOCTYPE declaration like this:
        <!DOCTYPE language SYSTEM "language.dtd">

        You can validate your syntax files using checkXML from the development
        package of kdelibs:
         checkXML yourSyntax.xml
        If you see any 'validity error' lines, you should fix them. If you get
        a lot of 'No template matches' lines, everything's just fine. You've
        produced a valid syntax file!

        It's also possible to use the (much faster) xmllint which comes with the
        GNOME (oops:-) XML Library libxml2:

         xmllint - -dtdvalid language.dtd yourSyntax.xml
	 (don't use a space between the two - That's just because XML
         comments don't allow that:-(

        To use your syntax file, copy it to .kde/share/apps/katepart/syntax/ in
        your home directory. You have to open a new instance of kwrite/kate to use
        the new syntax file.

TODO
  - find a more readable way for the - -dtdvalid stuff, it's just annoying
    xml comments don't allow it.
-->

<!-- Entity declarations
  You can use '&per;' instead of '.'. This seems to be useful in <item> elements.

TODO
  - Are there any more such pre-defined entities?
-->
<!ENTITY per "." >

<!-- Boolean type
  Attributes that are of type boolean allow the following values:
  'true', 'TRUE' and '1' all meaning true,
  'false', FALSE' and '0' all meaning false.

  It is encouraged to use 'true' and 'false' instead of the alternatives.
-->
<!ENTITY % boolean "true|false|TRUE|FALSE|0|1">

<!-- Language specification
  name:        The name of this syntax description. Used in the Highlightning Mode menu
  section:     The logical group to which this syntax description belongs. Used for sub menus
  extensions:  A file glob or pattern to decide for which documents to use this syntax description
  mimetype:    A list of mimetypes to decide for which documents to use this syntax description [optional]
  version:     Version number of this syntax description [optional]
  kateversion: Kate version required for using this file [optional]
  casesensitive: Whether text is matched case sensitive. [boolean, optional, default=false]
  priority:    Priority of this language, if more than one are usable for the file [optional]
  author:      Name of author of this hl file [optional]
  license:     License for this hl file [optional]
  hidden:      Should it be hidden in menu [boolean, optional, default=false]

TODO
  - Which matches are affected by casesensitive? keyword, RegExpr, StringDetect...?

WARNING: due to helper scripts, the language opening tag must be on a 
*single line* and *cannot* be split in multiple lines.

-->
<!ELEMENT language (highlighting, general?)>
<!ATTLIST language
  name          CDATA       #REQUIRED
  section       NMTOKEN     #REQUIRED
  extensions    CDATA       #REQUIRED
  mimetype      CDATA       #IMPLIED
  version       CDATA       #IMPLIED
  kateversion   CDATA       #IMPLIED
  casesensitive (%boolean;) #IMPLIED
  priority      CDATA       #IMPLIED
  author        CDATA       #IMPLIED
  license       CDATA       #IMPLIED
  hidden        (%boolean;) #IMPLIED
>

<!-- General options -->
<!ELEMENT general (comments|keywords)*>

<!-- List of comments -->
<!ELEMENT comments (comment)+>

<!-- Comment specification
  name:         Type of this comment. Allowed are 'singleLine' and 'multiLine'
  start:        The comment starts with this string
  end:          The comment ends with this string [optional]
-->
<!ELEMENT comment EMPTY>
<!ATTLIST comment
  name      (singleLine|multiLine)  #REQUIRED
  start     CDATA                   #REQUIRED
  end       CDATA                   #IMPLIED
>

<!-- Keyword options
  casesensitive:        Whether keywords are matched case sensitive. [boolean, optional, default=false]
  weakDeliminator:      Add weak deliminators [optional]
  additionalDeliminator: Add deliminators [optional]

TODO
  - Explain (weak) deliminators
-->
<!ELEMENT keywords EMPTY>
<!ATTLIST keywords
  casesensitive         CDATA   #IMPLIED
  weakDeliminator       CDATA   #IMPLIED
  additionalDeliminator CDATA   #IMPLIED
>

<!-- Highlighting specification -->
<!ELEMENT highlighting (list*, contexts, itemDatas)>
<!ATTLIST highlighting
>

<!-- List of items
  name:     Name of this list
-->
<!ELEMENT list (item)*>
<!ATTLIST list
  name  CDATA   #REQUIRED
>

<!-- List item
  contains string used in <keyword>
-->
<!ELEMENT item (#PCDATA)>

<!-- List of contexts -->
<!ELEMENT contexts (context)+>

<!-- context specification
  name:             The name of this context specification. Used in '*Context' attributes [optional]
  attribute:        The name of the ItemData to be used for matching text
  lineEndContext:   Next context if end of line is encountered
  lineBeginContext: Next context if begin of line is encountered [optional]
  fallthrough:      Use a fallthrough context [optional]
  fallthroughContext: Fall through to this context [optional]
  dynamic:          Dynamic context [boolean, optional]

TODO:
  - Explain fallthrough.
  - Do we need fallthrough at all? It could be true, if fallthroughContext is set, false otherwhise.
  - Make lineEndContext optional, defaults to '#stay'. Reasonable?
-->
<!ELEMENT context (keyword | Float | HlCOct | HlCHex | HlCFloat | Int | DetectChar | Detect2Chars | AnyChar | StringDetect | RegExpr | LineContinue | HlCStringChar | RangeDetect | HlCChar | IncludeRules)*>
<!ATTLIST context
  name              CDATA       #IMPLIED
  attribute         CDATA       #REQUIRED
  lineEndContext    CDATA       #REQUIRED
  lineBeginContext  CDATA       #IMPLIED
  fallthrough       (%boolean;) #IMPLIED
  fallthroughContext CDATA      #IMPLIED
  dynamic           (%boolean;) #IMPLIED
>

<!-- Common attributes
  attribute:    The name of the ItemData to be used for matching text
  context:      The name of the context to go to when this rule matches
  beginRegion:  Begin a region of type beginRegion [optional]
  endRegion:    End a region of type endRegion [optional]
-->
<!ENTITY % commonAttributes
 "attribute     CDATA       #REQUIRED
  context       CDATA       #REQUIRED
  beginRegion   CDATA       #IMPLIED
  endRegion     CDATA       #IMPLIED
  lookAhead     (%boolean;) #IMPLIED"
>

<!-- Detect members of a keyword list
  commonAttributes: Common attributes
  String:           Name of the list
  weakDelimiter:    Use weak deliminator

TODO:
  - Should be weakDeliminator
  - Explain deliminator
  - Doesn't seem to be suported in highligh.cpp
-->
<!ELEMENT keyword EMPTY>
<!ATTLIST keyword
  %commonAttributes;
  String    CDATA   #REQUIRED
  weakDelimiter CDATA #IMPLIED
>

<!-- Detect a floating point number
  commonAttributes: Common attributes
-->
<!ELEMENT Float (AnyChar)*>
<!ATTLIST Float
  %commonAttributes;
>

<!-- Detect an octal number
  commonAttributes: Common attributes
-->
<!ELEMENT HlCOct EMPTY>
<!ATTLIST HlCOct
  %commonAttributes;
>

<!-- Detect a hexadecimal number
  commonAttributes: Common attributes
-->
<!ELEMENT HlCHex EMPTY>
<!ATTLIST HlCHex
  %commonAttributes;
>

<!-- Detect a C-style floating point number
  commonAttributes: Common attributes
-->
<!ELEMENT HlCFloat EMPTY>
<!ATTLIST HlCFloat
  %commonAttributes;
>

<!-- Detect C-style character
  commonAttributes: Common attributes

TODO
  - Did I get this right?
-->
<!ELEMENT HlCChar EMPTY>
<!ATTLIST HlCChar
  %commonAttributes;
>

<!-- Detect an integer number
  commonAttributes: Common attributes
-->
<!ELEMENT Int (StringDetect)*>
<!ATTLIST Int
  %commonAttributes;
>

<!-- Detect a single character
  commonAttributes: Common attributes
  char:             The character to look for
  dynamic:          Uses 0 ... 9 as placeholders for dynamic arguments (in fact, first char of arg...) [boolean, optional, default=false]
-->
<!ELEMENT DetectChar EMPTY>
<!ATTLIST DetectChar
  %commonAttributes;
  char          CDATA   #REQUIRED
  dynamic       (%boolean;) #IMPLIED
>

<!-- Detect two characters
  commonAttributes: Common attributes
  char:             The first character
  char1:            The second character
  dynamic:          Uses 0 ... 9 as placeholders for dynamic arguments (in fact, first char of arg...) [boolean, optional, default=false]
-->
<!ELEMENT Detect2Chars EMPTY>
<!ATTLIST Detect2Chars
  %commonAttributes;
  char          CDATA   #REQUIRED
  char1         CDATA   #REQUIRED
  dynamic       (%boolean;) #IMPLIED
>

<!-- Detect any group of characters
  commonAttributes: Common attributes
  String:           A string representing the characters to look for

TODO
  - Description is not descriptive enough, I'm not sure what it exactly does:-(
-->
<!ELEMENT AnyChar EMPTY>
<!ATTLIST AnyChar
  %commonAttributes;
  String        CDATA   #REQUIRED
>

<!-- Detect a string
  commonAttributes: Common attributes
  String:           The string to look for
  insensitive:      Whether the string is matched case INsensitive. [boolean, optional, default=false]
  dynamic:          Uses %0 ... %9 as placeholders for dynamic arguments [boolean, optional, default=false]

TODO
  - What's default of insensitive? I'm not sure...
-->
<!ELEMENT StringDetect EMPTY>
<!ATTLIST StringDetect
  %commonAttributes;
  String        CDATA       #REQUIRED
  insensitive   (%boolean;)  #IMPLIED
  dynamic       (%boolean;) #IMPLIED
>

<!-- Detect a match of a regular expression
  commonAttributes: Common attributes
  String:           The regular expression pattern
  insensitive:      Whether the text is matched case INsensitive. [boolean, optional, default=false]
  minimal:          Wheather to use minimal matching for wild cards in the pattern [boolean, optional, default='false']
  dynamic:          Uses %0 ... %9 as placeholders for dynamic arguments [boolean, optional, default=false]
-->
<!ELEMENT RegExpr EMPTY>
<!ATTLIST RegExpr
  %commonAttributes;
  String        CDATA       #REQUIRED
  insensitive   (%boolean;) #IMPLIED
  minimal       (%boolean;) #IMPLIED
  dynamic       (%boolean;) #IMPLIED
>

<!-- Detect a line continuation
  commonAttributes: Common attributes
-->
<!ELEMENT LineContinue EMPTY>
<!ATTLIST LineContinue
  %commonAttributes;
>

<!-- Detect a C-style escaped character
  commonAttributes: Common attributes

TODO:
  - Did I get this right? Only one character, or a string?
-->
<!ELEMENT HlCStringChar EMPTY>
<!ATTLIST HlCStringChar
  %commonAttributes;
>

<!-- Detect a range of characters
  commonAttributes: Common attributes
  char:             The character starting the range
  char1:            The character terminating the range
-->
<!ELEMENT RangeDetect EMPTY>
<!ATTLIST RangeDetect
  %commonAttributes;
  char          CDATA   #REQUIRED
  char1         CDATA   #REQUIRED
>

<!-- Include Rules of another context
  context:             The name of the context to include
  includeAttrib:       If this is true, the host context of the IncludeRules
                       will be given the attribute of the source context
-->
<!ELEMENT IncludeRules EMPTY>
<!ATTLIST IncludeRules
  context       CDATA   #REQUIRED
  includeAttrib (%boolean;) #IMPLIED
>

<!-- List of attributes -->
<!ELEMENT itemDatas (itemData)+>
<!ATTLIST itemDatas
>

<!-- Attribute specification
  name          CDATA   #REQUIRED       The name of this attribute
  defStyleNum   CDATA   #REQUIRED       The index of the default style to use
  color         CDATA   #IMPLIED        Color for this style, either a hex triplet, a name or some other format recognized by Qt [optional]
  selColor      CDATA   #IMPLIED        The color for this style when text is selected [optional]
  italic        CDATA   #IMPLIED        Whether this attribute should be rendered using an italic typeface [optional, boolean, default=false]
  bold          CDATA   #IMPLIED        Whether this attribute should be renederd using a bold typeface [optional, boolean, default=false]
  underline     CDATA   #IMPLIED        Whether this attribute should be underlined [optional, boolean, default=false]
  strikeout     CDATA   #IMPLIED        Whether this attribute should be striked out [optional, boolean, default=false]
-->
<!ELEMENT itemData EMPTY>
<!ATTLIST itemData
  name          CDATA   #REQUIRED
  defStyleNum   CDATA   #REQUIRED
  color         CDATA   #IMPLIED
  selColor      CDATA   #IMPLIED
  italic        (%boolean;) #IMPLIED
  bold          (%boolean;) #IMPLIED
  underline     (%boolean;) #IMPLIED
  strikeout     (%boolean;) #IMPLIED
>

=== chrizel/Yzis/syntax/tibasic.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="TI Basic" version="1.00" kateversion="2.3" section="Scripts" priority="9">
  <highlighting>
    <list name="keywords" casesensitive="0">
      <item>If </item>
      <item>Then </item>
      <item>Else </item>
      <item>For </item>
      <item>While </item>
      <item>Repeat </item>
      <item>End </item>
      <item>Pause </item>
      <item>Lbl </item>
      <item>Goto </item>
      <item>IS&gt; </item>
      <item>DS&lt; </item>
      <item>Menu </item>
      <item>prgm </item>
      <item>Return </item>
      <item>DelVar </item>
      <item>GraphStyle </item>
      <item>Input </item>
      <item>Prompt </item>
      <item>Disp </item>
      <item>DispGraph </item>
      <item>DispTable </item>
      <item>Output </item>
      <item>getKey </item>
      <item>ClrHome </item>
      <item>ClrTable </item>
      <item>GetCalc </item>
      <item>Get </item>
      <item>Send</item>
      <item>prgm</item>
    </list>
    <list name="special_sym">
      <item>net</item>
      <item>eogt</item>
      <item>eolt</item>
      <item>sqrt</item>
      <item>%THETA</item>
    </list>
    <contexts>
      <context attribute="Normal Text" lineEndContext="#stay" name="Normal">
        <keyword attribute="Keyword" context="#stay" String="keywords"/>
        <keyword attribute="Special operators" context="#stay" String="special_sym" />

        <Detect2Chars attribute="Assignment" context="#stay" char="-" char1="&gt;"/>
        <StringDetect attribute="Assignment" context="#stay" String="st"/>

        <RegExpr attribute="Matrix" context="#stay" String="\[[\w]\]" />
        <DetectChar attribute="String" context="String" char="&quot;"/>
      </context>
      <context attribute="String" lineEndContext="#stay" name="String">
        <DetectChar attribute="String" context="#pop" char="&quot;"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text"  defStyleNum="dsNormal"/>
      <itemData name="Assignment" defStyleNum="dsAssign" />
      <itemData name="Keyword" defStyleNum="dsKeyword" />
      <itemData name="String" defStyleNum="dsString" />
      <itemData name="Special operators" defStyleNum="dsSpecOp" />
      <itemData name="Matrix" defStyleNum="dsMatrix" />
    </itemDatas>
  </highlighting>
</language>

=== chrizel/Yzis/syntax/mediawiki.xml
<?xml version = '1.0' encoding = 'UTF-8'?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Wikimedia" section="Markup" version="1.00" kateversion="2.4" extensions="" mimetype="" license="FDL" >
  <highlighting>
    <contexts>
      <context attribute="Normal" lineEndContext="#stay" name="normal" >
        <StringDetect String="&lt;!--" context="comment" attribute="Comment" beginRegion="comment" />
        <RegExpr String="([=]{2,2}[^=]+[=]{2,2}|[=]{3,3}[^=]+[=]{3,3}|[=]{4,4}[^=]+[=]{4,4}|[=]{5,5}[^=]+[=]{5,5})" attribute="Section" column="0" />
        <RegExpr String="[~]{3,4}" attribute="Wiki-Tag" context="#stay" />
        <RegExpr String="[*#;:\s]*[*#:]+" attribute="Wiki-Tag" context="#stay" column="0" />
        <RegExpr String="[[](?![[])" attribute="Wiki-Tag" context="URL" />
        <RegExpr String="(http:|ftp:|mailto:)[\S]*($|[\s])" attribute="URL" context="#stay" />
        <RegExpr String="[']{2,}" attribute="Wiki-Tag" context="#stay" />
        <Detect2Chars char="{" char1="|" context="Table" attribute="Wiki-Tag" column="0" beginRegion="table" />
        <Detect2Chars char="{" char1="{" context="Template" attribute="Wiki-Tag" />
        <Detect2Chars char="[" char1="[" context="WikiLink" attribute="Wiki-Tag" />
        <RangeDetect char="&amp;" char1=";" attribute="HTML-Entity" context="#stay" />
        <StringDetect String="&lt;nowiki&gt;" context="NoWiki" attribute="Wiki-Tag" />
        <StringDetect String="&lt;pre&gt;" context="Pre" attribute="HTML-Tag" />
        <RegExpr String="[&lt;][^&gt;]+[&gt;]" attribute="HTML-Tag" context="#stay" />
        <RegExpr String="[\s]" context="Unformatted" column="0" />
      </context>
      <context attribute="Normal" lineEndContext="#stay" name="Table" >
        <StringDetect String="&lt;!--" context="comment" attribute="Comment" />
        <RegExpr String="([=]{2,2}[^=]+[=]{2,2}|[=]{3,3}[^=]+[=]{3,3}|[=]{4,4}[^=]+[=]{4,4}|[=]{5,5}[^=]+[=]{5,5})" attribute="Section" context="#stay" column="0" />
        <RegExpr String="[*#;:\s]*[*#:]+" attribute="Wiki-Tag" context="#stay" column="0" />
        <RegExpr String="[[](?![[])" context="URL" attribute="Wiki-Tag" />
        <RegExpr String="(http:|ftp:|mailto:)[\S]*($|[\s])" attribute="URL" context="#stay" />
        <RegExpr String="[']{2,}" attribute="Wiki-Tag" context="#stay" />
        <Detect2Chars char="|" char1="}" context="#pop" attribute="Wiki-Tag" column="0" endRegion="table" />
        <DetectChar char="|" attribute="Wiki-Tag" context="#stay"/>
        <Detect2Chars char="{" char1="{" context="Template" attribute="Wiki-Tag" />
        <Detect2Chars char="[" char1="[" context="WikiLink" attribute="Wiki-Tag" />
        <RangeDetect char="&amp;" char1=";" attribute="HTML-Entity" context="#stay" />
        <StringDetect String="&lt;nowiki&gt;" context="NoWiki" attribute="Wiki-Tag" />
        <StringDetect String="&lt;pre&gt;" context="Pre" attribute="HTML-Tag" />
        <RegExpr String="[&lt;][^&gt;]+[&gt;]" attribute="HTML-Tag" context="#stay" />
        <RegExpr String="[\s]" context="Unformatted" column="0" />
        <RegExpr String="[~]{3,4}" attribute="Wiki-Tag" context="#stay" />
        <RegExpr String="[-]{4,}" attribute="Wiki-Tag" context="#stay" />
        <DetectChar char="!" attribute="Wiki-Tag" context="#stay" column="0" />
      </context>
      <context attribute="Comment" lineEndContext="#stay" name="comment" >
        <StringDetect String="--&gt;" context="#pop" attribute="Comment" endRegion="comment" />
      </context>
      <context attribute="Link" lineEndContext="#stay" name="URL" >
        <DetectChar char="]" context="#pop" attribute="Wiki-Tag" />
        <DetectChar char="'" context="Error" attribute="Error" />
      </context>
      <context attribute="Link" lineEndContext="#stay" name="WikiLink" >
        <DetectChar char="|" attribute="Wiki-Tag" context="#stay" />
        <Detect2Chars char="]" char1="]" context="#pop" attribute="Wiki-Tag" />
        <DetectChar char="'" context="Error" attribute="Error" />
      </context>
      <context attribute="Template" lineEndContext="#stay" name="Link" >
        <Detect2Chars char="}" char1="}" context="#pop" attribute="Wiki-Tag" />
        <AnyChar String="'[]" context="Error" attribute="Error" />
      </context>
      <context attribute="Error" lineEndContext="#pop" name="Error" />
      <context attribute="Link" lineEndContext="#stay" name="Template" >
        <Detect2Chars char="}" char1="}" context="#pop" attribute="Wiki-Tag" />
        <DetectChar char="'" context="Error" attribute="Error" />
      </context>
      <context attribute="NoWiki" lineEndContext="#stay" name="NoWiki" >
        <RegExpr String="&lt;!--[^-]*--&gt;" attribute="NoWiki" />
        <StringDetect String="&lt;/nowiki&gt;" context="#pop" attribute="Wiki-Tag" />
        <RegExpr String="[&lt;][^&gt;]+[&gt;]" attribute="HTML-Tag" context="#stay" />
        <StringDetect String="&lt;pre&gt;" context="Pre" attribute="HTML-Tag" />
      </context>
      <context attribute="Unformatted" lineEndContext="#pop" name="Unformatted" />
      <context attribute="NoWiki" lineEndContext="#stay" name="Pre" >
      <StringDetect String="&lt;/pre&gt;" context="#pop" attribute="Wiki-Tag" />
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal" defStyleNum="dsNormal" />
      <itemData name="Link" defStyleNum="dsOthers" />
      <itemData name="URL" defStyleNum="dsOthers" />
      <itemData name="Comment" defStyleNum="dsComment" />
      <itemData name="Section" defStyleNum="dsKeyword" />
      <itemData name="HTML-Entity" defStyleNum="dsDecVal" />
      <itemData name="HTML-Tag" defStyleNum="dsKeyword" />
      <itemData name="Wiki-Tag" defStyleNum="dsDecVal" bold="true" />
      <itemData name="Error" defStyleNum="dsError" />
      <itemData name="NoWiki" defStyleNum="dsNormal" />
      <itemData name="Unformatted" defStyleNum="dsNormal" />
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment end="//-->" start="&lt;!--" name="multiLine" />
    </comments>
    <keywords casesensitive="0" />
  </general>
</language>

=== chrizel/Yzis/syntax/lua.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE language SYSTEM "language.dtd">
<language name="Lua" version="0.22" kateversion="2.3" section="Scripts" extensions="*.lua" mimetype="text/x-lua">
  <highlighting>
    <list name="keywords">
      <item> and </item>
      <item> end </item>
      <item> local </item>
      <item> return </item>
      <item> break </item>
      <item> for </item>
      <item> do </item>
      <item> if </item>
      <item> nil </item>
      <item> then </item>
      <item> function </item>
      <item> not </item>
      <item> until </item>
      <item> else </item>
      <item> or </item>
      <item> while </item>
      <item> elsif </item>
      <item> in </item>
      <item> repeat </item>
    </list>
    <list name="basefunc">
      <item> string.byte </item>
      <item> string.char </item>
      <item> string.find </item>
      <item> string.len </item>
      <item> string.lower </item>
      <item> string.rep </item>
      <item> string.sub </item>
      <item> string.upper </item>
      <item> string.format </item>
      <item> string.gfind </item>
      <item> string.gsub </item>
      <item> table.concat </item>
      <item> table.foreach </item>
      <item> table.foreachi </item>
      <item> table.getn </item>
      <item> table.sort </item>
      <item> table.insert </item>
      <item> table.remove </item>
      <item> table.setn </item>
      <item> math.abs </item>
      <item> math.sin </item>
      <item> math.cos </item>
      <item> math.tan </item>
      <item> math.asin </item>
      <item> math.acos </item>
      <item> math.atan </item>
      <item> math.atan2 </item>
      <item> math.ceil </item>
      <item> math.floor </item>
      <item> math.mod </item>
      <item> math.frexp </item>
      <item> math.ldexp </item>
      <item> math.squrt </item>
      <item> math.min </item>
      <item> math.max </item>
      <item> math.log </item>
      <item> math.log10 </item>
      <item> math.exp </item>
      <item> math.deg </item>
      <item> math.rad </item>
      <item> math.random </item>
      <item> math.randomseed </item>
      <item> io.close </item>
      <item> io.flush </item>
      <item> io.input </item>
      <item> io.lines </item>
      <item> io.open </item>
      <item> io.output </item>
      <item> io.read </item>
      <item> io.stderr </item>
      <item> io.stdin </item>
      <item> io.stdout </item>
      <item> io.tmpfile </item>
      <item> io.write </item>
      <item> os.clock </item>
      <item> os.date </item>
      <item> os.difftime </item>
      <item> os.execute </item>
      <item> os.exit </item>
      <item> os.getenv </item>
      <item> os.remove </item>
      <item> os.rename </item>
      <item> os.setlocale </item>
      <item> os.time </item>
      <item> os.tmpname </item>
      <item> debug.getinfo </item>
      <item> debug.getlocal </item>
      <item> debug.setlocal </item>
      <item> debug.sethook </item>
      <item> debug.gethook </item>
      <item> assert </item>
      <item> collectgarbage </item>
      <item> dofile </item>
      <item> error </item>
      <item> next </item>
      <item> print </item>
      <item> rawget </item>
      <item> rawset </item>
      <item> tonumber </item>
      <item> tostring </item>
      <item> type </item>
      <item> _ALERT </item>
      <item> _ERRORMESSAGE </item>
      <item> call </item>
      <item> copytagmethods </item>
      <item> dostring </item>
      <item> foreach </item>
      <item> foreachi </item>
      <item> getglobal </item>
      <item> getn </item>
      <item> gettagmethod </item>
      <item> globals </item>
      <item> newtag </item>
      <item> setglobal </item>
      <item> settag </item>
      <item> settagmethod </item>
      <item> sort </item>
      <item> tag </item>
      <item> tinsert </item>
      <item> tremove </item>
      <item> openfile </item>
      <item> closefile </item>
      <item> flush </item>
      <item> seek </item>
      <item> setlocale </item>
      <item> execute </item>
      <item> remove </item>
      <item> rename </item>
      <item> tmpname </item>
      <item> getenv </item>
      <item> date </item>
      <item> clock </item>
      <item> exit </item>
      <item> readfrom </item>
      <item> writeto </item>
      <item> appendto </item>
      <item> read </item>
      <item> write </item>
      <item> abs </item>
      <item> sin </item>
      <item> cos </item>
      <item> tan </item>
      <item> asin </item>
      <item> acos </item>
      <item> atan </item>
      <item> atan2 </item>
      <item> ceil </item>
      <item> floor </item>
      <item> mod </item>
      <item> frexp </item>
      <item> ldexp </item>
      <item> squrt </item>
      <item> min </item>
      <item> max </item>
      <item> log </item>
      <item> log10 </item>
      <item> exp </item>
      <item> deg </item>
      <item> rad </item>
      <item> random </item>
      <item> randomseed </item>
      <item> strlen </item>
      <item> strsub </item>
      <item> strlower </item>
      <item> strupper </item>
      <item> strchar </item>
      <item> strrep </item>
      <item> ascii </item>
      <item> strbyte </item>
      <item> format </item>
      <item> strfind </item>
      <item> gsub </item>
      <item> getinfo </item>
      <item> getlocal </item>
      <item> setlocal </item>
      <item> setcallhook </item>
      <item> setlinehook </item>
      <item> getglobals </item>
      <item> getmetatable </item>
      <item> gcinfo </item>
      <item> ipairs </item>
      <item> loadfile </item>
      <item> loadstring </item>
      <item> pairs </item>
      <item> pcall </item>
      <item> require </item>
      <item> setglobals </item>
      <item> setmetatable </item>
      <item> unpack </item>
      <item> LUA_PATH </item>
      <item> _LOADED </item>
      <item> _VERSION </item>
    </list>
    <contexts>
      <context attribute="Normal Text" lineEndContext="#stay" name="Normal">
        <keyword attribute="Keyword" context="#stay" String="keywords" />
        <keyword attribute="BaseFunc" context="#stay" String="basefunc"/>
        <HlCChar attribute="Char" context="#stay"/>
        <Detect2Chars attribute="Comment" context="Comment" char="-" char1="-"/>
        <DetectChar attribute="Comment" context="Comment" char="#"/>
        <DetectChar attribute="String" context="String" char="&quot;"/>
        <AnyChar attribute="Symbol" context="#stay" String="!%&amp;()+,-&lt;=&gt;?[]^{|}~"/>
        <RegExpr attribute="Number" context="#stay" String="\d*\.?\d*e?\d+"/>
      </context>
      <context attribute="Comment" lineEndContext="#pop" name="Comment">
        <RegExpr attribute="Alert" context="#stay" String="(FIXME|TODO)" />
      </context>
      <context attribute="String" lineEndContext="#pop" name="String">
        <DetectChar attribute="String" context="#pop" char="&quot;"/>
      </context>
    </contexts>
    <itemDatas>
      <itemData name="Normal Text" defStyleNum="dsNormal"/>
      <itemData name="Keyword"  defStyleNum="dsKeyword"/>
      <itemData name="Comment" defStyleNum="dsComment"/>
      <itemData name="String" defStyleNum="dsString"/>
      <itemData name="Decimal" defStyleNum="dsDecVal"/>
      <itemData name="Number" defStyleNum="dsBaseN"/>
      <itemData name="Symbol" defStyleNum="dsNormal"/>
      <itemData name="BaseFunc" defStyleNum="dsNormal" color="#0095FF" selColor="#FFFFFF" bold="1" italic="0"/>
      <itemData name="Alert" defStyleNum="dsAlert" />
    </itemDatas>
  </highlighting>
  <general>
    <comments>
      <comment name="singleLine" start="--" />
    </comments>
    <keywords casesensitive="1" weakDeliminator="&#46;" additionalDeliminator="&quot;"/>
  </general>
</language>
<!-- kate: space-indent on; indent-width 2; replace-tabs on; -->
